### ISSUE TITLE
[お題リポジトリ改善] Templateリポジトリ化すると良さそう

### ISSUE THREAD

**Issue by nabemasamasa** [daniel-software-tokyo/console-calendar#8]
「Fork」でなくても、TemplateRepositoryなら`Use this template`から`Create a new repository`すると、TemplateRepositoryをベースに自分のリポジトリの生成画面が表示される。(RepositoryNameとかPublicOrPrivateとかの画面…)

![image](https://user-images.githubusercontent.com/20126608/205522426-b9ba0b31-930d-48f2-b007-d63f8f8e8a98.png)

また、Issueの生成をGitHubActionで自動生成できるようにするともっと良さそう。

↓こんな感じ
```yml
name: "Create issues from sessions"

runs:
  using: "composite"

  steps:

    - uses: peter-evans/create-issue-from-file@v4
      with:
        title: Session0
        content-filepath: docs/sessions/setup.md
```
